<?php
$not_found = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.5,12C18,12 20,14 20,16.5C20,17.38 19.75,18.21 19.31,18.9L22.39,22L21,23.39L17.88,20.32C17.19,20.75 16.37,21 15.5,21C13,21 11,19 11,16.5C11,14 13,12 15.5,12M15.5,14A2.5,2.5 0 0,0 13,16.5A2.5,2.5 0 0,0 15.5,19A2.5,2.5 0 0,0 18,16.5A2.5,2.5 0 0,0 15.5,14M7,15V17H9C9.14,18.55 9.8,19.94 10.81,21H5C3.89,21 3,20.1 3,19V5C3,3.89 3.89,3 5,3H19A2,2 0 0,1 21,5V13.03C19.85,11.21 17.82,10 15.5,10C14.23,10 13.04,10.37 12.04,11H7V13H10C9.64,13.6 9.34,14.28 9.17,15H7M17,9V7H7V9H17Z" /></svg> ' . $wo["lang"]["no_result"] . '</div>';
$type_to_find = '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M9.62,12L12,5.67L14.37,12M11,3L5.5,17H7.75L8.87,14H15.12L16.25,17H18.5L13,3H11Z" /></svg> ' . $wo["lang"]["what_are_looking_for"] . '</div>';

$page = isset($_GET['page-id']) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$db->pageLimit = 20;
$link = '';
$products = $db->objectbuilder()->orderBy('id','DESC')->paginate(T_PRODUCTS, $page);


?>
<div class="page-margin">
	<div class="page-margin mt-0">
		<div class="wow_content popular_posts_hdr">
			<h2 class="flex">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" class="icon_main" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M17 17h-11v-14h-2"></path><path d="M6 5l14 1l-1 7h-13"></path></svg>&nbsp;
				<p>
				    <?php /* echo $wo['lang']['welcome_discover'] */ ?> 
				    <?php echo !empty($wo['lang']['market']) 
                        ? 'Catalog' 
                        : $wo['lang']['market']; 
                    ?>
				    <b>
				        <?php echo !empty($wo['lang']['explore_a_curated_marketplace']) 
                            ? 'Explore unique finds, uncover hidden gems and meet exceptional creators.' 
                            : $wo['lang']['explore_a_curated_marketplace'];
                        ?>

				    </b>
				</p>
			</h2>
		</div>
		
		
		 <div class="col-md-3 leftcol">
			<div class="market_prnt"><?php echo Wo_LoadPage("directory/left-sidebar"); ?></div>
		</div>
		
		
	</div>
	
    <div class="row">
        <div class="col-md-9 singlecol">
            
            
            <div class="page-margin wow_content wow_big_head_link flex">
            	<ul class="list-unstyled">
            	    
            	    <li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>" data-ajax="?link1=products"><?php echo 'All Products';?></a></li>
            	    
            		<?php if ($wo['loggedin'] == true && $wo['config']['can_use_market']) { ?>
            			<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products"><?php echo $wo['lang']['my_products'];?></a></li>
            		<?php } ?>
            		
            		<?php if ($wo['config']['store_system'] == 'on') { ?>
            			<li><a href="<?php echo Wo_SeoLink('index.php?link1=purchased'); ?>" data-ajax="?link1=purchased"><?php echo $wo['lang']['purchased'] ?></a></li>
            		<?php } ?>
            		
            		<?php if ($wo['config']['store_system'] == 'on') { ?>
            			<li><a href="<?php echo Wo_SeoLink('index.php?link1=orders'); ?>" data-ajax="?link1=orders"><?php echo 'Received Orders' ?></a></li>
            		<?php } ?>
            
            	</ul>
            	
            	<div class="right_part">
            		<div class="search-blog">
            			<form action="">
            				<?php
            					$placeholder = $wo['lang']['search_for_products_main'];
            					if (!empty($category_name)) {
            						$placeholder = str_replace('{category_name}', $category_name, $wo['lang']['search_for_products']);
            					}
            				?>
            				<input type="text" onkeyup="Wo_SearchProducts(this.value)" placeholder="<?php echo $placeholder; ?>" id="product-text">
            				<svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="9" cy="9" r="8" stroke="currentColor" stroke-width="2"/><path d="M14.5 15.5L18.5 19.5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
            			</form>
            		</div>
            	
            		<div class="dropdown market_widget">
            			<div class="btn btn-mat btn-main dropdown-toggle" data-toggle="dropdown" role="button">
            				<svg width="16" height="18" viewBox="0 0 16 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.0086 1.5H2.99063C1.64578 1.5 0.862648 3.03017 1.6428 4.13351L5.05925 8.96527C5.45848 9.52988 5.67302 10.2058 5.67302 10.899V14.2744C5.67302 15.5036 6.6623 16.5 7.88264 16.5C9.10298 16.5 10.0923 15.5036 10.0923 14.2744V10.9488C10.0923 10.2248 10.3262 9.52062 10.7588 8.94251L14.3301 4.16979C15.1518 3.07156 14.374 1.5 13.0086 1.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M10.0923 10.7458C10.0923 10.0374 10.3262 9.34833 10.7588 8.78264L14.3301 4.11244C15.1518 3.0378 14.374 1.5 13.0086 1.5H2.99063C1.64578 1.5 0.862648 2.9973 1.6428 4.07694L5.05925 8.80491C5.45848 9.35739 5.67302 10.0188 5.67302 10.6971V14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
            			</div>
            			<div class="dropdown-menu dropdown-menu-right">
            				<div class="market_widget">
            					<div class="m_widget_head">
            						<?php echo $wo['lang']['sort_by'];?>
            					</div>
            
            					<div class="market_categories">
            						<ul class="product-sort-slider">
            							<li class="active" onclick="changePriceSortValue('latest');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $wo['lang']['latest'] ?></a></li>
            							<li onclick="changePriceSortValue('price_low');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $wo['lang']['price_low'] ?></a></li>
            							<li onclick="changePriceSortValue('price_high');$(this).addClass('active');"><a href="javascript:void(0)"><?php echo $wo['lang']['price_high'] ?></a></li>
            						</ul>
            					</div>
            				</div>
            				<div class="market_widget">
            					<div class="m_widget_head">
            						<?php echo $wo['lang']['categories'];?>
            					</div>
            
            					<div class="market_categories">
            						<ul class="product-category-slider">
            							<?php 
            								$category_id = (!empty($_GET['c_id'])) ? (int) $_GET['c_id'] : 0;
            								foreach ($wo['products_categories'] as $key => $category) {
            									$active = ($category_id == $key) ? 'active' : '';
            							?>
            								<li class="<?php echo $active?>" data_prodect_cat_id="<?php echo($key) ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=products&c_id=' . $key);?>"><?php echo $category;?></a></li>
            							<?php } ?>
            						</ul>
            					</div>
            				</div>
            				<?php if ( !empty($_GET['c_id']) && !empty($wo['products_sub_categories'][$_GET['c_id']])) { ?>
            					<div class="market_widget">
            						<div class="m_widget_head">
            							<?php echo $wo['lang']['sub_category'];?>
            						</div>
            
            						<div class="market_categories">
            							<ul class="product-category-slider-sub">
            								<?php 
            									$category_id = (!empty($_GET['sub_id'])) ? (int) $_GET['sub_id'] : 0;
            									foreach ($wo['products_sub_categories'][$_GET['c_id']] as $key => $category) {
            										$active = ($category_id == $category['id']) ? 'active' : '';
            								?>
            									<li class="<?php echo $active?>" data_prodect_cat_id="<?php echo($category['id']) ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=products&c_id=' . $_GET['c_id'].'&sub_id='.$category['id']);?>"><?php echo $category['lang'];?></a></li>
            								<?php } ?>
            							</ul>
            						</div>
            					</div>
            				<?php } ?>
            				<div class="market_widget">
            					<div class="m_widget_head">
            						<?php echo $wo['lang']['location_dist'];?>
            					</div>
            					
            					<div class="select-nearby-users-distance">
            						<form>
            							<input type="range" class="cusrange" id="nearby-users-distance" name="amountRange" onchange="Wo_SearchProductsNearBy();" value="0" min="0" max="300" oninput="this.form.amountInput.value=this.value">
            							<input type="number" name="amountInput" min="0" max="4000" value="0" oninput="this.form.amountRange.value=this.value" readonly id="cusrange-reader"/> km
            						</form>
            					</div>
            				</div>
            				<?php if ($wo['loggedin'] == true) { ?>
            				<?php if ($wo['config']['nearby_shop_system'] == 1) { ?>
            					<a href="<?php echo($wo['config']['site_url'].'/nearby_shops') ?>" data-ajax="?link1=nearby_shops" class="btn btn-block btn-main btn-mat side_mkt_btn"><?php echo $wo['lang']['nearby_shops'] ?></a>
            				<?php } ?>
            				<?php } ?>
            			</div>
            		</div>
            	</div>
            	
        	</div>
            
            
            <div class="products wo_market direct_market">
                <div class="latest-products">
                    <div class="market_bottom">
                        <?php
                        if (count($products) > 0) {
                        ?>
                        <div id="products" class="row">
                            <?php
                            foreach ($products as $key => $wo['product']) {
                                $wo['product'] = (array) $wo['product'];
                                $wo['product'] = Wo_GetProduct($wo['product']['id']);
                                echo Wo_LoadPage('products/products-list');
                            }
                            } else {
                                echo '<div class="col-md-12"><div class="wow_content"><div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,13A5,5 0 0,1 7,8H9A3,3 0 0,0 12,11A3,3 0 0,0 15,8H17A5,5 0 0,1 12,13M12,3A3,3 0 0,1 15,6H9A3,3 0 0,1 12,3M19,6H17A5,5 0 0,0 12,1A5,5 0 0,0 7,6H5C3.89,6 3,6.89 3,8V20A2,2 0 0,0 5,22H19A2,2 0 0,0 21,20V8C21,6.89 20.1,6 19,6Z"></path></svg>' . $wo['lang']['no_available_products'] . '</div></div></div>';
                            }
                            ?>
                        </div>
                    </div>

                    <?php if (!empty($products)) { ?>
                        <div class="wo-admincp-feturepager">
                            <div class="">
                        <span>
                          <?php echo "Showing $page out of " . $db->totalPages; ?>
                        </span>
                            </div>
                            <div class="">
                                <nav>
                                    <ul class="pagination">
                                        <li>
                                            <a href="<?php echo Wo_Link('directory/market?page-id=1') . $link; ?>"
                                               data-ajax="?link1=directory-market&page-id=1<?php echo($link); ?>"
                                               class="waves-effect" title='First Page'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M11 7l-5 5l5 5"></path><path d="M17 7l-5 5l5 5"></path></svg>
                                            </a>
                                        </li>
                                        <?php if ($page > 1) { ?>
                                            <li>
                                                <a href="<?php echo Wo_Link('directory/market?page-id=' . ($page - 1)) . $link; ?>"
                                                   data-ajax="?link1=directory-market&page-id=<?php echo ($page - 1) . $link; ?>"
                                                   class="waves-effect" title='Previous Page'>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M15 6l-6 6l6 6"></path></svg>
                                                </a>
                                            </li>
                                        <?php } ?>

                                        <?php
                                        $nums = 0;
                                        $nums_pages = ($page > 4) ? ($page - 4) : $page;

                                        for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                                            if ($nums < 20) {
                                                ?>
                                                <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                    <a href="<?php echo Wo_Link('directory/market?page-id=' . ($i)) . $link; ?>"
                                                       data-ajax="?link1=directory-market&page-id=<?php echo ($i) . $link; ?>"
                                                       class="waves-effect">
                                                        <?php echo $i ?>
                                                    </a>
                                                </li>

                                            <?php }
                                            $nums++;
                                        } ?>

                                        <?php if ($db->totalPages > $page) { ?>
                                            <li>
                                                <a href="<?php echo Wo_Link('directory/market?page-id=' . ($page + 1)) . $link; ?>"
                                                   data-ajax="?link1=directory-market&page-id=<?php echo ($page + 1) . $link; ?>"
                                                   class="waves-effect" title="Next Page">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 6l6 6l-6 6"></path></svg>
                                                </a>
                                            </li>
                                        <?php } ?>
                                        <li>
                                            <a href="<?php echo Wo_Link('directory/market?page-id=' . ($db->totalPages)) . $link; ?>"
                                               data-ajax="?link1=directory-market&page-id=<?php echo($db->totalPages) ?><?php echo($link); ?>"
                                               class="waves-effect" title='Last Page'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M7 7l5 5l-5 5"></path><path d="M13 7l5 5l-5 5"></path></svg>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    <?php } ?>


                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<script>


    jQuery(document).ready(function ($) {

    });
</script>