<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	'All orders' => array(
		__( 'All orders', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Orders filtered by creation date' => array(
		__( 'Orders filtered by creation date', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Orders filtered by completed date' => array(
		__( 'Orders filtered by completed date', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Orders filtered by paid date' => array(
		__( 'Orders filtered by paid date', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'No orders found.' => array(
		__( 'No orders found.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Error' => array(
		__( 'Error', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Close' => array(
		__( 'Close', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Applying rules to orders' => array(
		__( 'Applying rules to orders', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'%1$s / %2$s orders processed.' => array(
		__( '%1$s / %2$s orders processed.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Process completed!' => array(
		__( 'Process completed!', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Rules applied to %s orders.' => array(
		__( 'Rules applied to %s orders.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Apply rules to orders' => array(
		__( 'Apply rules to orders', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Apply to' => array(
		__( 'Apply to', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'From' => array(
		__( 'From', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'To' => array(
		__( 'To', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Applying...' => array(
		__( 'Applying...', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Apply' => array(
		__( 'Apply', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Apply rules' => array(
		__( 'Apply rules', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Untitled' => array(
		__( 'Untitled', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Confirm delete' => array(
		__( 'Confirm delete', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Are you sure you want to delete the "%s" rule?' => array(
		__( 'Are you sure you want to delete the "%s" rule?', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'This action cannot be undone and you will not be able to recover this data.' => array(
		__( 'This action cannot be undone and you will not be able to recover this data.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'No' => array(
		__( 'No', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Yes, delete' => array(
		__( 'Yes, delete', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Saving...' => array(
		__( 'Saving...', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Save' => array(
		__( 'Save', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Edit rule' => array(
		__( 'Edit rule', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Rule name' => array(
		__( 'Rule name', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'User role assignment' => array(
		__( 'User role assignment', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'The user will gain the role' => array(
		__( 'The user will gain the role', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'The user will switch the role' => array(
		__( 'The user will switch the role', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'When' => array(
		__( 'When', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'User purchases a specific product' => array(
		__( 'User purchases a specific product', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Order total is within the following price range' => array(
		__( 'Order total is within the following price range', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Customer\'s total spend falls within the following price range' => array(
		__( 'Customer\'s total spend falls within the following price range', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'User purchases products from specific categories or tags' => array(
		__( 'User purchases products from specific categories or tags', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Product to purchase' => array(
		__( 'Product to purchase', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Select a product' => array(
		__( 'Select a product', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Set a price range' => array(
		__( 'Set a price range', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Tags' => array(
		__( 'Tags', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Categories' => array(
		__( 'Categories', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Schedule rule' => array(
		__( 'Schedule rule', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Enable to set a start/end date for this rule.' => array(
		__( 'Enable to set a start/end date for this rule.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Enable role expiration' => array(
		__( 'Enable role expiration', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Enable to set an expiration in days for this rule.' => array(
		__( 'Enable to set an expiration in days for this rule.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'The role will be switched back in' => array(
		__( 'The role will be switched back in', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'days' => array(
		__( 'days', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'day' => array(
		__( 'day', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Exclude users' => array(
		__( 'Exclude users', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Enable to exclude users for this rule.' => array(
		__( 'Enable to exclude users for this rule.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Roles to exclude' => array(
		__( 'Roles to exclude', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Add rule' => array(
		__( 'Add rule', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'You have no rules!' => array(
		__( 'You have no rules!', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'The rule name cannot be empty.' => array(
		__( 'The rule name cannot be empty.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Please, select a role.' => array(
		__( 'Please, select a role.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Please, select the roles.' => array(
		__( 'Please, select the roles.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Please, select a product.' => array(
		__( 'Please, select a product.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Please, select either a minimum or maximum price.' => array(
		__( 'Please, select either a minimum or maximum price.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Please, select at least one tag or category.' => array(
		__( 'Please, select at least one tag or category.', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Type to search...' => array(
		__( 'Type to search...', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'No results for "%s".' => array(
		__( 'No results for "%s".', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Searching...' => array(
		__( 'Searching...', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Leaving this page now will discard the changes. Are you sure you want to proceed?' => array(
		__( 'Leaving this page now will discard the changes. Are you sure you want to proceed?', 'yith-automatic-role-changer-for-woocommerce' ),
	),
	'Modal titleCreate new rule' => array(
		_x( 'Create new rule', 'Modal title', 'yith-automatic-role-changer-for-woocommerce' ),
	),
);