<?php 
$pages = Wo_GetCustomPages();
?>
<div class="page-margin">
	<div class="footer-wrapper">
		<hr>
		<div class="footer-powered">
			<p>
				<?php 
					$copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
					echo $copy = str_replace('{date}', date('Y'), $copy);
				?>
			</p>
			<ul class="list-inline">
				<li><a href="<?php echo $wo['config']['site_url'];?>" data-ajax="?link1=home"><?php echo $wo['lang']['home'];?></a></li>
				<li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>" data-ajax="?link1=terms&type=about-us"><?php echo $wo['lang']['about'];?></a></li>
				<li><a href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>" data-ajax="?link1=contact-us"><?php echo $wo['lang']['contact_us'];?></a></li>
				<li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>" data-ajax="?link1=terms&type=privacy-policy"><?php echo $wo['lang']['privacy_policy'];?></a></li>
				<li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>" data-ajax="?link1=terms&type=terms"><?php echo $wo['lang']['terms_of_use'];?></a></li>
				<?php if ($wo['config']['refund_system'] == 'on') { ?>
					<li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=refund');?>" data-ajax="?link1=terms&type=refund"><?php echo $wo['lang']['request_refund'];?></a></li>
				<?php } ?>
				
				<?php  if ($wo['config']['blogs'] == 1) { ?>
					<li><a href="<?php echo Wo_SeoLink('index.php?link1=blogs');?>" data-ajax="?link1=blogs"><?php echo $wo['lang']['blog'];?></a></li>
				<?php }?>
				<?php if ($wo['config']['developers_page'] == 1)  { ?>
					<li><a data-ajax="?link1=developers" href="<?php echo Wo_SeoLink('index.php?link1=developers');?>"><?php echo $wo['lang']['developers'];?></a></li>
				<?php } ?>
				<?php if (count($pages) > 0) { ?>
					<li>
						<div class="dropdown dropup">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
								<?php echo $wo['lang']['more'];?> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu" style="width: auto; min-width: 100px; font-size: 11px;">
								<?php
									if (count($pages) > 0) {
									foreach ($pages as $key => $page) {
								?>
									<li><a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a></li>
								<?php } } ?>
							</ul>
						</div>
					</li> 
				<?php } ?>
			</ul>
			<ul class="lang_selct">
				<li>
					<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="modal" data-target="#select-language">
						<svg height="13" viewBox="0 0 24 24" width="13" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg> <?php echo $wo['lang']['language'];?>
					</a>
				</li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
    <!--Blue Crown R&D: Footer Menu-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://koware.org/footer-menu/footer-menu.css">
    
    <div class="bottom-footer-menu">
        <ul>
    			<li><a href="/streams/messages"><i class="fa fa-comments"></i> Chat</a></li>
                <li><a href="/streams/common_things"><i class="fa fa-th-list"></i> Blogs</a></li>
                <li><a href="/streams"><i class="fa fa-image"></i> Streams</a></li>
                <li><a href="/"><i class="fa fa-home"></i> Cabin</a></li>
                <li><a href="/courses"><i class="fa fa-leanpub"></i> Courses</a></li>
                <li><a href="/social/login"><i class="fa fa-users"></i> Social</a></li>
                <li><a href="/streams/setting"><i class="fa fa-tachometer"></i> Dashboard</a></li>
        </ul>
    </div>
	
</div>

