<?php
defined( 'ABSPATH' ) || exit;
// Auto-generated. Do not edit by hand.

return array(
    'source_url' => 'https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json',
    'fetched_at' => '2026-09-07T04:06:30+00:00',
    'checksum' => 'sha256:31a238e012515714e8921e205c5808782cbe486085d51a20821d87128a050a2a',
    'signatures' => array(
        'AI2Bot',
        'AI2Bot-DeepResearchEval',
        'AIWebIndex',
        'AddSearchBot',
        'AgentTimes',
        'Ai2Bot-Dolma',
        'AmazonBuyForMe',
        'Amazonbot',
        'Amzn-SearchBot',
        'Amzn-User',
        'Andibot',
        'Anomura',
        'ApifyBot',
        'ApifyWebsiteContentCrawler',
        'Aranet-SearchBot',
        'Awario',
        'AzureAI-SearchBot',
        'Bravebot',
        'Brightbot',
        'Brightbot 1.0',
        'BuddyBot',
        'Bytespider',
        'CCBot',
        'Channel3Bot',
        'ChatGLM-Spider',
        'ChatGPT Agent',
        'ChatGPT-User',
        'Claude-Code',
        'Claude-SearchBot',
        'Claude-User',
        'Claude-Web',
        'ClaudeBot',
        'CloudVertexBot',
        'Cloudflare-AutoRAG',
        'Code',
        'Cotoyogi',
        'CragCrawler',
        'Crawl4AI',
        'Crawlspace',
        'Cursor',
        'Datenbank Crawler',
        'DeepSeekBot',
        'Devin',
        'Diffbot',
        'Diffbot-User',
        'DoubaoBot',
        'DuckAssistBot',
        'ERNIEBot',
        'Echobot Bot',
        'EchoboxBot',
        'ExaBot',
        'ExaSearchBot',
        'FacebookBot',
        'Factset_spyderbot',
        'FirecrawlAgent',
        'FriendlyCrawler',
        'GPTBot',
        'GeistHaus-PageFetcher',
        'Gemini-Deep-Research',
        'Google-Agent',
        'Google-CloudVertexBot',
        'Google-Extended',
        'Google-Firebase',
        'Google-Gemini-CLI',
        'Google-NotebookLM',
        'GoogleAgent-Mariner',
        'GoogleAgent-URLContext',
        'GoogleOther',
        'GoogleOther-Image',
        'GoogleOther-Video',
        'HenkBot',
        'ICC-Crawler',
        'ISSCyberRiskCrawler',
        'ImagesiftBot',
        'Kangaroo Bot',
        'Kimi-SearchBot',
        'Kimi-User',
        'KimiBot',
        'KlaviyoAIBot',
        'KunatoCrawler',
        'LAIONDownloader',
        'Lightpanda',
        'LinerBot',
        'Linguee Bot',
        'LinkupBot',
        'Manus-User',
        'Meta-ExternalAgent',
        'Meta-ExternalFetcher',
        'MistralAI-Index',
        'MistralAI-Training',
        'MistralAI-User',
        'MistralAI-User/1.0',
        'Mozilla-Tabstack',
        'MyCentralAIScraperBot',
        'NagetBot',
        'NotebookLM',
        'NovaAct',
        'OAI-AdsBot',
        'OAI-SearchBot',
        'OpenAI',
        'Operator',
        'PanguBot',
        'Panscient',
        'Perplexity-User',
        'PerplexityBot',
        'PhindBot',
        'Poggio-Citations',
        'Poseidon Research Crawler',
        'QualifiedBot',
        'Querit-SearchBot',
        'QueritBot',
        'QuillBot',
        'QwenBot',
        'Reflectionbot',
        'SBIntuitionsBot',
        'Scrapy',
        'SemrushBot-OCOB',
        'SemrushBot-SWA',
        'Shap-User',
        'ShapBot',
        'Sidetrade indexer bot',
        'Spider',
        'TavilyBot',
        'Terra Cotta',
        'TerraCotta',
        'Thinkbot',
        'TikTokSpider',
        'Timpibot',
        'TongyiBot',
        'Trae',
        'TwinAgent',
        'UseAI',
        'VelenPublicWebCrawler',
        'WARDBot',
        'WRTNBot',
        'Webzio-Extended',
        'YandexAdditional',
        'YandexAdditionalBot',
        'YiyanBot',
        'YouBot',
        'ZanistaBot',
        'aiHitBot',
        'amazon-QBusiness',
        'amazon-kendra',
        'anthropic-ai',
        'atlassian-bot',
        'bedrockbot',
        'bigsur.ai',
        'cohere-ai',
        'cohere-training-data-crawler',
        'iAskBot',
        'iaskspider',
        'iaskspider/2.0',
        'imageSpider',
        'img2dataset',
        'kagi-fetcher',
        'laion-huggingface-processor',
        'meta-externalagent',
        'meta-externalfetcher',
        'netEstate Imprint Crawler',
        'newsai',
        'omgili',
        'omgilibot',
        'opencode',
        'panscient.com',
        'quillbot.com',
        'webzio-extended',
        'wpbot',
    ),
);
