<?php
defined( 'ABSPATH' ) || exit;
// Auto-generated. Do not edit by hand.

return array(
    'source_url' => 'MANUAL (provider docs)',
    'fetched_at' => '2026-09-03T10:53:55+00:00',
    'checksum' => 'sha256:14f84ef96bcc1402f68779422306d2a2dd7ea9e25a4593ca80d1f4192f1ec670',
    'signatures' => array(
        'AdIdxBot',
        'AdsBot-Google',
        'Applebot',
        'Applebot-Extended',
        'Baiduspider',
        'Baiduspider-image',
        'BingPreview',
        'Bingbot',
        'DuckDuckBot',
        'Google-InspectionTool',
        'Googlebot',
        'Googlebot-Image',
        'Googlebot-News',
        'Googlebot-Video',
        'Mediapartners-Google',
        'MicrosoftPreview',
        'MojeekBot',
        'NaverBot',
        'PetalBot',
        'SeznamBot',
        'Sogou',
        'Sogou web spider',
        'Storebot-Google',
        'YandexBot',
        'YandexImages',
        'YandexMobileBot',
        'Yeti',
        'facebookexternalhit',
        'meta-externalads',
        'meta-webindexer',
    ),
);
